### ISSUE TITLE
35.2节错误未处理

### ISSUE THREAD

**Issue by adophper** [ffhelicopter/Go42#10]
35.2节方法err未处理
func tHandler(w http.ResponseWriter, r *http.Request) {
	t, err := template.ParseFiles("layout.html.tmpl", "index.html.tmpl")
	t.ExecuteTemplate(w, "layout", "Hello World!")
}

**Comment by ffhelicopter** [comment]
对的，这里对err没有做处理，不太妥。其实本书很多地方都没有对err做处理，是担心篇幅过长，还请谅解。实际开发中我们还是要尽量完善对err的处理。
