### ISSUE TITLE
defer可以再补充点

### ISSUE THREAD

**Issue by xinxindu** [ffhelicopter/Go42#29]
如果defer的代码块放在了函数退出代码的后面，那么defer中的代码块也是是无法执行到的

**Comment by ffhelicopter** [comment]
不知能否具体举例说明，多谢了！

在这种条件语句中有可能执行不到defer：
func t(i int) int {
	fmt.Println(i)
	i++
	if i > 0 {
		return i
	} else {
		defer func() {
			fmt.Println(i)
		}()
		return i
	}

}

**Comment by xinxindu** [comment]
因为自己踩过坑，所以贴出来，让大家注意一下，谢谢笔者总结。
例子：
func TestDefer() {
	fmt.Println("start")
	panic("generate panic.")

	defer func() {                // defer是无法执行的,导致recover是无效的 
		ret := recover()
		if ret != nil {
			fmt.Println("TestDefer panic")
		} else {
			fmt.Println("TestDefer has no panic")
		}
	}()
}

**Comment by ffhelicopter** [comment]
多谢说明。这是因为在Go中规定：panic之前需要先声明好defer。

----------------------------------------------
15.2 Panic

在Go语言中 panic 是一个内置函数，用来表示非常严重的不可恢复的错误。必须要先声明defer，否则不能捕获到panic异常。
