### ISSUE TITLE
字典 map 那章 “所以数组、函数、字典、切片和结构体不能作为 key”，其实数组可以作为 key 存在

### ISSUE THREAD

**Issue by manmanxing** [ffhelicopter/Go42#32]
```go
func main() {
	map2 := make(map[[2]int]interface{})
	array := [2]int{1,2}
	map2[array] = 1
	fmt.Println(map2)
}
```
可以正常输出

**Comment by ffhelicopter** [comment]
这里表述的确不够严谨，实际上的情况是：数组元素的数据类型是内建类型如int等是可以比较的，数组也能作为key。但数组元素的类型如果是type自定义的类型，则是不能做为key的，后面括号中结构体做key，分别对这两种情况作了说明。你所说的情况是属于前者，有兴趣你可以改为自定义类型试试。

关于Key，最关键的是这句话，key 可以是任意可以用 == 或者 != 操作符比较的类型，比如 string、int、float。
