### ISSUE TITLE
第二十三章 同步与锁 程序输出是否有误？

### ISSUE THREAD

**Issue by wisecsj** [ffhelicopter/Go42#5]
原版：
```
程序输出：
Locking  (G0)
locked (G0)
Locking (G1)
Locking (G3)
Locking (G2)
ready unlock (G0)
unlocked (G0)
locked (G1)
unlocked (G1)
locked (G3)
locked (G2)
unlocked (G3)
unlocked (G2)
```
输出不应该是locked g3,unlock g3,再去locked g2么?

**Comment by wisecsj** [comment]
难道是因为g3刚刚unlock，还未执行print，就被调度器切换去执行g2所在goroutine么？

**Comment by ffhelicopter** [comment]
@wisecsj 这里程序输出是可能出现的（我在写本节时是多次运行才捕获这个结果的），正如你后面说的原因。当然如果把time.Sleep(time.Second * 2)注释掉可能出现连续显示locked的概率要小一些。我们这里主要理解资源被mutex.Lock()后，只有mutex.Unlock()后，才能被其他协程使用。
