### ISSUE TITLE
更新goroutine的runtime源码

### ISSUE THREAD

**Issue by eternal-flame-AD** [ffhelicopter/Go42#6]
Go已经实现自举，g,m,p struct定义在[这里](https://golang.org/src/runtime/runtime2.go#L339)，[原文](https://github.com/ffhelicopter/Go42/blob/master/content/42_21_goroutine.md)对C代码的引用已经不存在。

**Comment by ffhelicopter** [comment]
多谢提醒，我找时间更新下。
