### ISSUE TITLE
Go slice 不是指针，而是包含指针的结构体

### ISSUE THREAD

**Issue by isLishude** [ffhelicopter/Go42#7]
第12章，slice的介绍基本是错的。

> 绝对不要用指针指向 slice，切片本身已经是一个引用类型，所以它本身就是一个指针!

```go
package main

import "fmt"

func main() {
	x := []int{0, 0, 0}
	test(x)
	fmt.Println(x)
}

func test(i []int) {
	i = []int{1, 2, 3}
}
```

输出 `[0 0 0]`，如果按照作者的理论 slice 是指针的话，结果应该是 `[1 2 3]`。

错太多了，建议作者再读读 https://blog.golang.org/go-slices-usage-and-internals

**Comment by ffhelicopter** [comment]
我尝试着来解释下这句话和您的代码运行结果。

解释这句话：绝对不要用指针指向 slice，切片本身已经是一个引用类型，所以它本身就是一个指针!

是想表达下面注释掉的语句是有问题的：
x := []int{0, 0, 0}  
// x := *[]int{0, 0, 0}

您的代码为什么会出现这个结果，因为涉及到Go函数的传值和传引用问题，和变量本身的引用不是一个问题，而Go函数的参数传递是传值，很容易导致我们的误解。下面test，test2,test3可以说明在Go中传参和引用类型变量的区别和作用。

package main

import "fmt"

func main() {
	x := []int{0, 0, 0}
	//x := *[]int{0, 0, 0}
	test(x)
	fmt.Println(x)
	var xx = &x
	fmt.Println((*xx)[0])
	//fmt.Println(xx[0])

	//test2(&x)
	//fmt.Println(x)
	test3(x)
	fmt.Println(x)
}

func test(i []int) {
	i = []int{1, 2, 3}
}

func test2(i *[]int) {
	*i = []int{1, 2, 3}
}

func test3(i []int) {
	i[1] = 999
}


另外，可以可以使用unsafe.Pointer跟踪下您代码中test(i)，i的地址以及x的地址，应该是不一样。

**Comment by isLishude** [comment]
不想讨论这个问题了。

**Comment by isLishude** [comment]
昨天就没看你长篇大论，今天在看你是连最基本的指针和取引用符号都分不清，少年，你还是好好学习下吧，你说的都是错的，别扯什么传引用和传指针。

**Comment by isLishude** [comment]
自己研究源码吧，看看是不是指针或者什么引用，还是我说的，是包含指针的结构体https://github.com/golang/go/blob/master/src/runtime/slice.go#L13

```go
type slice struct {
	array unsafe.Pointer
	len   int
	cap   int
}
```

**Comment by ffhelicopter** [comment]
由于slice变量的特殊性（sli 是结构体变量，但sli[0]直接指向了底层数组的第一个元素），而且这句话表述得词不达意，会导致严重歧义，特删掉该句。
多谢提醒！

**Comment by ilaziness** [comment]
@ffhelicopter 
@islishude 他说的没错，创建一个slice实际是一个值`slice`，是值类型，不是一个引用`*slice`，不要和引用底层数组这个引用搞混了。
你文章里面"所以切片是一个引用类型"，“切片是引用”是不恰当的，是引用的那就是`*slice`类型，实际是`slice`类型。

旧版go创建一个slice是返回一个`slice`类型，新版go是返回一个`sliceheader`类型。

这里有篇文章：https://segmentfault.com/a/1190000042430248?utm_source=sf-similar-article
